version: '2'

volumes:
  sqlserver_local: {}
  sqlserver_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: dbasurveillance_local_django
    depends_on:
      - mssql
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.mssql
    ports:
      - "8000:8000"
    command: /start.sh


  mssql:
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: "g0lfc@pture"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_local:/var/opt/mssql/
      - sqlserver_backups:/backups
    env_file:
      - ./.envs/.local/.mssql





