# Generated by Django 2.0.6 on 2018-06-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('key', models.AutoField(db_column='InstanceKey', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='InstanceName', max_length=128)),
                ('virtual_server_name', models.CharField(db_column='VirtualServerName', max_length=128)),
                ('clustered', models.BooleanField(db_column='Clustered')),
                ('node', models.CharField(db_column='Node', max_length=128)),
                ('edition', models.CharField(db_column='Edition', max_length=100)),
                ('product_level', models.CharField(db_column='ProductLevel', max_length=100)),
                ('product_version', models.CharField(db_column='ProductVersion', max_length=100)),
            ],
            options={
                'db_table': 'DimInstances',
                'managed': False,
            },
        ),

    ]
