# Generated by Django 2.0.6 on 2018-07-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlreports', '0003_auto_20180702_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
