# Generated by Django 2.0.6 on 2018-07-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlreports', '0005_auto_20180702_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='van',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
