# Generated by Django 2.0.6 on 2018-07-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlreports', '0006_auto_20180702_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
