# Generated by Django 2.0.6 on 2018-09-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SqlCounter',
            fields=[
                ('key', models.AutoField(db_column='SqlCounterKey', primary_key=True, serialize=False)),
                ('instance', models.CharField(blank=True, db_column='InstanceName', max_length=200, null=True)),
                ('counter', models.CharField(blank=True, db_column='SqlCounter', max_length=200, null=True)),
                ('area', models.CharField(blank=True, db_column='InstanceArea', max_length=200, null=True)),
                ('node', models.CharField(blank=True, db_column='Node', max_length=128, null=True)),
                ('start_date', models.DateField(blank=True, db_column='Startdate', null=True)),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
            ],
            options={
                'db_table': 'DimSqlCounters',
                'managed': False,
            },
        ),
    ]
